    FROM node:16-alpine3.13
    EXPOSE 5000
    WORKDIR /usr/src/app
    COPY ./example-frontend .
    ENV REACT_APP_BACKEND_URL="http://127.0.0.1:8080"
    RUN npm install && \
        npm run build && \
        npm install -g serve && \
        rm -rf node_modules && \
        adduser -D kayttaja

    # non-root user
    USER kayttaja

    CMD ["serve","-s","-l","5000","build"]

    