version: '3' 

services:
    front:  
        image: etukontti
        ports:
            - 5000:5000
    back:
        image: takakontti
        ports:
            - 8080:8080
        environment: 
            REDIS_HOST: oma_redis
            POSTGRES_HOST: postgres_db
            POSTGRES_USER: tietokantailija
            POSTGRES_PASSWORD: salasana
            POSTGRES_DATABASE: postgres
            # ADDED THIS:
            #   REQUEST_ORIGIN: http://localhost
            # As i kept encountering CORS issues thought adding this would help.
            # And it did.
            REQUEST_ORIGIN: http://localhost
    redis-db:
        image: redis
        ports:
            - 6379:6379
        container_name: oma_redis
        volumes:
            - ./redis-data:/data
    postgres-db:
        image: postgres:13.3-alpine
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: tietokantailija
            POSTGRES_PASSWORD: salasana
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
    proxy:
        image: nginx:1.21.0-alpine
        container_name: e_proxy
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf