version: '3' 

services:
    front:  
        image: etukontti
        ports:
            - 5000:5000
    back:
        image: takakontti
        ports:
            - 8080:8080
        environment: 
            REDIS_HOST: oma_redis
    redis-db:
        image: redis
        ports:
            - 6379:6379
        container_name: oma_redis